project_id = "vcmfvmspymqzwqyxjepi"

[functions.send-notification-email]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.get-vapid-key]
verify_jwt = false

[functions.onfido-create-applicant]
verify_jwt = true

[functions.onfido-webhook]
verify_jwt = false
